import Config from 'react-native-config';
import Logo from './assets/images/Logo.png';
import Logo505 from './assets/images/Logo_505.png';
import LogoTern from './assets/images/LogoTern.png';
import Logo6226 from './assets/images/6226.png';
import Logo981 from './assets/images/981.png';
import Logo334 from './assets/images/334.png';
import LogoLana from './assets/images/Lana.jpg';
import LogoVip223 from './assets/images/LogoVip223.jpg';
import LogoLviv from './assets/images/LogoLviv.jpg';
import LogoLoka from './assets/images/loka.jpg';

const config = {
  khmel: {
    app_name: 'Ok.2299',
    app_logo: Logo,
    app_logoLong: false,
    app_currency: '\u20B4',
    app_url: 'ws://2299.fas.taxi:6444/ws/client',
    app_token: 'nJdGTUdHFGHb2aFBY2BCBCx3',
    app_host: '2299.fas.taxi',
    // app_url: 'ws://devel.fas.taxi:8444/ws/client',
    // app_token: '700400',
    // app_host: 'devel.fas.taxi',
    // app_url: 'ws://demo.fas.taxi:9554/ws/client',
    // app_token: 'nkzUfKdR25GrGqKx5frJ8SfZ',
    // app_host: 'demo.fas.taxi',
    app_color: '#F3E852',
    app_colorText: '#110F27',
    package_name_android: 'com.oktaxi',
    package_name_ios: 'com.oktaxi2299',
    package_id: '1484088157',
    package_link: 'ok2299.page.link',
    app_promo: '2299.com.ua',
    app_uk: true,
    senderId: '689994155912',
  },
  donetsk: {
    app_name: 'Такси 505 Донецк',
    app_logo: Logo505,
    app_logoLong: false,
    app_currency: '\u20BD',
    app_port: '8444',
    app_host: '505.fas.taxi',
    app_url: `ws://505.fas.taxi:8444/ws/client`,
    app_color: '#ffe500',
    app_colorText: '#110F27',
    app_token: 'h76mr8xh4Cbt7XtCzHHV',
    package_name_android: 'com.taxi505.client',
    package_name_ios: 'com.taxi505',
    package_link: '505taxi.page.link',
    package_id: '1483936733',
    app_promo: '',
    app_uk: false,
    senderId: '30706890275',
  },
  ternopil: {
    app_name: 'Таксі Комфорт Тернопіль',
    app_logo: LogoTern,
    app_logoLong: true,
    app_currency: '\u20B4',
    app_port: '6444',
    app_host: '2299.fas.taxi',
    app_url: `ws://2299.fas.taxi:6444/ws/client`,
    app_color: '#203dc9',
    app_colorText: '#FFFFFF',
    app_token: 'DvkmykqJNzUswfHXn69j',
    package_name_android: 'it.stocksoft.client2299tern',
    package_name_ios: 'it.stocksoft.client2299tern',
    package_id: '1483914460',
    package_link: '',
    app_promo: '',
    app_uk: true,
    senderId: '390479406386',
  },
  khmel6226: {
    app_name: 'Таксi 6226',
    app_logo: Logo6226,
    app_logoLong: false,
    app_currency: '\u20B4',
    app_url: 'ws://2299.fas.taxi:6444/ws/client',
    app_token: 'GhjbwBMERdFjfDStXNqkQzhJ',
    app_host: '2299.fas.taxi',
    app_color: '#110f27',
    app_colorText: '#FFFFFF',
    package_name_android: 'it.stocksoft.client6226khm',
    package_name_ios: 'it.stocksoft.client6226khm',
    package_id: '1491075395',
    package_link: '',
    app_promo: '',
    app_uk: true,
    senderId: '933965040940',
  },
  khmel981: {
    app_name: 'Таксi 981',
    app_logo: Logo981,
    app_logoLong: false,
    app_currency: '\u20B4',
    app_url: 'ws://2299.fas.taxi:6444/ws/client',
    app_token: 'BnTB8yfEdKPWJrcATmXmRMzg',
    app_host: '2299.fas.taxi',
    app_color: '#0e931f',
    app_colorText: '#FFFFFF',
    package_name_android: 'it.stocksoft.client981khm',
    package_name_ios: 'it.stocksoft.client981khm',
    package_id: '1491076959',
    package_link: '',
    app_promo: '',
    app_uk: true,
    senderId: '41566590583',
  },
  khmel334: {
    app_name: 'Таксi 334',
    app_logo: Logo334,
    app_logoLong: false,
    app_currency: '\u20B4',
    app_url: 'ws://2299.fas.taxi:6444/ws/client',
    app_token: 'qXrKkLuEbuy2gj3NwgED9L3j',
    app_host: '2299.fas.taxi',
    app_color: '#0e931f',
    app_colorText: '#FFFFFF',
    package_name_android: 'it.stocksoft.client334khm',
    package_name_ios: 'it.stocksoft.client334khm',
    package_id: '1491077095',
    package_link: '',
    app_promo: '',
    app_uk: true,
    senderId: '978908404151',
  },
  vipkp223: {
    app_name: "VIP Таксi Кам'янець-Подiльський",
    app_logo: LogoVip223,
    app_logoLong: false,
    app_currency: '\u20B4',
    app_url: 'ws://vipkp.fas.taxi:6444/ws/client',
    app_token: 'Y6ubj5XuaDsfYkJkX3gpK6Wz',
    app_host: 'vipkp.fas.taxi',
    app_color: '#0e931f',
    app_colorText: '#FFFFFF',
    package_name_android: 'it.stocksoft.vipkp223',
    package_name_ios: 'it.stocksoft.vipkp223',
    package_id: '1493063515',
    package_link: '',
    app_promo: '',
    app_uk: true,
    senderId: '942490930302',
  },
  lana: {
    app_name: 'Таксі Lana',
    app_logo: LogoLana,
    app_logoLong: false,
    app_currency: '\u20B4',
    app_url: 'ws://2299.fas.taxi:6444/ws/client',
    app_token: 'eUNTPgkb6KMNAZSqrAFxnYpr',
    app_host: '2299.fas.taxi',
    app_color: '#ffe500',
    app_colorText: '#110F27',
    package_name_android: 'it.stocksoft.clientLana',
    package_name_ios: 'it.stocksoft.clientLana',
    package_id: '1492628236',
    package_link: '',
    app_promo: '',
    app_uk: true,
    senderId: '580032638714',
  },
  lviv: {
    app_name: 'Економ 7070',
    app_logo: LogoLviv,
    app_logoLong: false,
    app_currency: '\u20B4',
    app_url: 'ws://7070lv.fas.taxi:6444/ws/client',
    app_token: 'ZfzLwYGh3aZLhzEUjsUUved4',
    app_host: '7070lv.fas.taxi',
    app_color: '#FFE600',
    app_colorText: '#110F27',
    package_name_android: 'it.stocksoft.clientLviv7070',
    package_name_ios: 'it.stocksoft.clientLviv7070',
    package_id: '1502395908',
    package_link: '',
    app_promo: '',
    app_uk: true,
    senderId: '206489506129',
  },
  loka: {
    app_name: 'Loka Taxi',
    app_logo: LogoLoka,
    app_logoLong: false,
    app_currency: '\u20AC',
    app_port: '6444',
    app_host: '2299.fas.taxi',
    app_url: `ws://2299.fas.taxi:6444/ws/client`,
    app_color: '#ffe500',
    app_colorText: '#110F27',
    app_token: 'DckYfvAjrhkyDSRqrcCE53eQ',
    package_name_android: 'it.stocksoft.lokataxi',
    package_name_ios: 'it.stocksoft.lokataxi',
    package_link: '',
    package_id: '1511255197',
    app_promo: '',
    app_uk: false,
    senderId: '178183096953',
  },
};

// const env = 'khmel';

// export default config[env];
export default config[Config?.APP_TARGET];
