import LocalizedStrings from 'react-native-localization';

export const strings = new LocalizedStrings({
  en: {
    welcome: 'Welcome',
    enterPhoneNumber: 'Enter phone',
    yourPromocode: 'Your promo code',
    howItsWorkText:
      'Share code {0} with friends and get {1} bonuses on your account. Person registered with the code gets {2} bonuses.',
    howItsWorkText1: 'Share code {0} with friends and get {1} bonuses on your account.',
    howItsWorkText2:
      'Share code {0} with friends. Person registered with the code gets {1} bonuses.',
    howItsWorkNoBonus: 'Share app and get bonuses from your friends trips.',
    howItWork: 'How it works?',
    refReward: "You will get {0} bonuses from every friend's trip.",
    refRewardPercent: "You will get {0}% from every friend's trip.",
    shareApp: 'Share the app',
    appLanguage: 'Language',
    defPayment: 'Payment default',
    defTariff: 'Default tariff',
    defTrip: 'Default trip',
    dontCallMe: "Don't call me",
    showActions: 'Show offers',
    noticeAboutshowPriceNotification: 'Notify me on price drop',
    logout: 'Logout',
    settings: 'Settings',
    removeAddress: 'Remove address?',
    addressWasRemoved: 'Address will be removed from Saved',
    remove: 'Remove',
    savedAddresses: 'Saved addresses',
    noSavedAddresses: 'You have no saved addresses',
    ifLeaveNoSave: "If you close this window address won't be saved",
    leaveWithoutSave: 'Quit without saving?',
    leave: 'Quit',
    return: 'Return',
    youCanFindAddress: 'You can find new address in the saved addresses.',
    addressSaved: 'The address has been saved',
    commentDriver: 'Comment to the driver',
    saveTheAddress: 'Save address',
    name: 'Name',
    approach: 'Entrance',
    cash: 'Cash',
    cashless: 'Cashless',
    order: 'Order',
    newTemplate: 'New template',
    cancel: 'Cancel',
    canceled: 'Canceled',
    create: 'Create',
    warning: 'Warning!',
    previous: 'Previous',
    planned: 'Planned',
    templates: 'Templates',
    finishYourRide: 'Complete the trip before a new order',
    yourHistoryEmpty: 'Missing trip history',
    noPlannedRides: 'Missing planned trips',
    noSavedTemplates: 'Missing saved templates',
    myTrips: 'My trips',
    enterYourData: 'Please fill in details for faster identification',
    userName: 'Name',
    userEmail: 'Email',
    userBirthday: 'Birthday',
    myFinances: 'My finances',
    information: 'Information',
    feedback: 'Feedback',
    profile: 'Profile',
    orderByPhone: 'Order by phone',
    allowGeodata: 'Allow location access for correct application work',
    userWrongCode: 'Invalid confirmation code. Enter the code carefully or change the number.',
    changePhoneNumber: 'Change phone number',
    codeReSend: 'Re-send the code in',
    repeatRequest: 'Repeat request',
    payWithCreditCard: 'Credit card',
    paymentMethod: 'Preferred payment method?',
    whereToGo: 'Where are we going?',
    areYouHere: 'Are you here?',
    outOfRun: 'The territory is out of service',
    comment: 'Comment',
    added: 'Added',
    add: 'Add',
    addService: 'Add. services',
    payment: 'Payment',
    orderNow: 'Order now',
    orderLater: 'Later',
    tripCanceled: 'Trip canceled',
    tripCancelReason: 'Cancellation reasons',
    bonusDebit20: '20 {0} deducted from your bonus account',
    cancelConfirm: 'Are you sure you want to cancel the trip?',
    cancelReasonDriverAsked: 'The driver asked to cancel',
    cancelReasonOrderByMistake: 'Ordered accidentally',
    cancelReasonWaitToLong: 'Too long to wait',
    cancelReasonUseAnotherTaxi: 'Took another taxi',
    cancelReasonDriverWrongWay: 'Driver went the wrong way',
    cancelReasonEnter: 'Please name a reason',
    cancelReasonChangePlans: 'Change plans',
    car: 'Car',
    trip: ' Trip',
    close: 'Close',
    startWrite: 'Start typing',
    save: 'Save',
    startAddress: 'Pick-up address',
    addressOfArrival: 'Delivery address',
    driverInPlace: 'Driver has arrived',
    driver: 'Driver',
    number: 'Number',
    color: 'Color',
    waitNear: 'Wait near',
    imlate: "I'm late",
    comeOut: 'On my way',
    timeInRoad: 'Trip time',
    cost: 'Cost',
    moreTaxi: 'Another taxi',
    infoText: 'Spacious cars and high-rated drivers',
    infoCarsText: 'Skoda Octavia, Ford Galaxy, Hyundai and 40 other',
    testimonials: 'Advantages',
    infoProsText: 'Spacious and comfortable cars',
    infoProsTolerant: 'Polite and tolerant drivers',
    infoProsHighRate: 'High-rated drivers',
    setComfortTime: 'Please indicate \nconvenient pick-up time,',
    via: 'Via',
    timeMin: 'min',
    date: 'Date',
    time: 'Time',
    setAlarm: 'Set reminder',
    noFreeCar: 'No free cars nearby',
    weCanOffer: 'We can offer',
    await: 'Wait',
    payCarOtherArea: 'Pay for car arrival from another area',
    callOtherCar: 'Request another car',
    checkOtherCarType: 'Choose another car class',
    extraOverPay: 'Extra-charge amount',
    overPay: 'Extra-charge',
    overPayComment: 'Note: Higher extra-charge leads to faster response from another area cars.',
    rideCost: 'Total trip cost',
    returnToMap: 'Back to the map',
    send: 'Send',
    yourRideIsOver: 'Your trip is complete',
    createNewTemplate: 'Create trip template',
    searchForCar: 'Looking for taxi',
    additionally: 'Additionally',
    services: 'services',
    tripFrom: 'From',
    tripTo: 'To',
    carClass: 'Car class',
    additionalServices: 'Additional Services',
    additionalServicesList: 'Check, Air Conditioning, Child seat, Tinting',
    orderStatus: 'Order status',
    changeAddress: 'Change address',
    filingCar: 'Arrival',
    chooseCreditCard: 'Choose credit card',
    addCreditCard: 'Add card',
    validTill: 'Expiry',
    saveCreditCard: 'Save the card',
    noAddress: 'No address',
    showOnMap: 'Point on the map',
    noInternet: 'No Internet connection',
    update: 'Update',
    confirm: 'OK',
    ok: 'OK',
    enterSendedCode: 'Enter the code sent to\n',
    enterValidEmail: 'Enter valid email',
    about: 'About the application',
    license: 'License agreement',
    privacyPolicy: 'Privacy',
    version: 'Version',
    hosted: 'Hosted',
    callback: 'Feedback',
    message: 'Message',
    feedbackSendSuccess: 'Message sent successfully',
    feedbackSendError: 'Message is not delivered, try again later',
    locationAccessHeader: 'We need to access your location',
    locationAccessRequest: 'We use your location to show where you are on the map',
    selectPhoto: 'Choose photo',
    servicesTravelTrunk: 'Empty trunk',
    servicesTinted: 'Toning',
    servicesConditioner: 'Conditioner',
    servicesTerminal: 'Terminal',
    servicesAnimals: 'Transportation of animals',
    servicesChildSeat: 'Child seat',
    servicesLowLanding: 'Low rider',
    servicesReceipt: 'Receipt',
    chooseAdditionalServices: 'Choose\n Additional services',
    servicesTripToFriend: 'Trip for friend',
    costOfTariff: ' of tariff cost',
    chat: 'Chat',
    onQuitPress: 'To exit double-click "Back"',
    statusSearching: 'Searching',
    statusAwaiting: 'Accepted',
    statusDriveOnPlace: 'Driver has arrived',
    statusInTheWay: 'On the way',
    ratingBadCar: 'Dirty car or car smelled bad',
    ratingLongRide: 'Has chosen a bad route or missed a turn',
    ratingLowSpeed: 'Drove too slowly',
    ratingTrafficRules: 'Violated traffic rules',
    ratingManyTalks: 'Talked a lot',
    ratingClientFeelBad: "Car driving caused client's sickness",
    ratingRideOnOtherCar: "Arrived car didn't meet requested demands",
    ratingRefuseHelpWithLuggage: 'Refused to help with luggage load',
    ratingAskedForGoodScore: 'Asked for high rates',
    ratingCallWithoutReason: 'Called unnecessarily',
    ratingWhyBadRating: 'Reasons for low rates?',
    rateTerribly: 'Awful',
    rateBadly: 'Bad',
    rateSatisfactorily: 'Satisfactorily',
    rateGood: 'Good',
    ratePerfectly: 'Excellent',
    rateARide: 'Rate the trip',
    taxiNotFound: 'Taxi not found',
    saved: 'Saved',
    popular: 'Popular',
    nearest: 'Nearest',
    secondAddressDidntSet:
      "You didn't indicate second address so it may take longer to search for a car.",
    result: 'Result',
    transactionCompleted: 'Transaction Successfully Completed',
    addCreditCardRequired: 'Credit Card required',
    distance: 'Distance',
    timeArrive: 'Delivery time',
    deleteCardConfirm: 'Delete card?',
    noCreditCard: 'Missing saved credit cards',
    address: 'Address',
    feedbackInfo: 'Write your wishes or complaints',
    map: 'Map',
    permissionDeniedTitle: 'Permission denied',
    permissionDeniedText: 'We need access to receive images from your camera or library.',
    permissionDeniedRetry: 're-try',
    permissionDeniedSure: "I'm sure",
    enterCode: 'Enter code',
    checkCode: "Please, check your code carefully, you can't change it after the registration",
    promoInput: 'If you have an promo code, press here',
    promo: 'Your promo code is',
    creditCard: 'Card',
    agree1: 'By continuing, you agree to ',
    agree2: 'license terms ',
    agree3: 'and ',
    agree4: 'privacy policy',
    loginLink1: 'For information display',
    loginLink2: 'log in to your account',
    pass: 'Skip',
    invalidCard: 'Invalid credit card number',
    invalidMonth: 'Invalid card expire month',
    invalidYear: 'Invalid card expire year',
    invalidDate: 'Invalid card expire date',
    invalidCvv: 'Invalid CVV',
    cardDecline: 'Card declined',
    error: 'Error',
    takePhoto: 'Take photo',
    chooseFromLibrary: 'Choose from Library',
    km: 'km.',
    m: 'm.',
    deleteTripConfirm: 'Are you sure you want to delete the trip from Previous?',
    deleteTemplateConfirm: 'Are you sure you want to delete the temlate?',
    onAccount: 'In your account',
    bonuses: 'bonuses',
    bonusPay: 'Bonuses',
    amountBonuses: 'Amount of bonuses',
    bonusLimit: 'Maximum bonus value exceeded',
    bonusLow: 'You do not have enough bonuses',
    bonusZero: 'Enter a number greater than 0',
    serviceCount: 'Services:',
    offerSurcharge: 'Offer surcharge',
    shareText: 'Download the application {0} and get a reward for the promotional code {1}\n{2}',
    shareTrip1: 'Order Taxi by the App',
    shareTrip2: 'go from',
    lateTime: 'For how long?',
    change: 'Change',
    activeTrips: 'Active trips',
    preordered: 'Preordered',
    reserved: 'Reserved',
    search: 'Search',
    noContacts: 'No contacts found',
    noActiveTrips: 'You have no active trips',
    addNumber: 'Add phone number',
    points: 'points',
    bonusesTab: 'My bonuses',
    myCards: 'My cards',
    usePromo: 'Use',
    enterPromo: 'Enter promocode',
    aboutPromo: 'Promocode lets you get a bonuses for your trips',
    promoFail: 'Promocode is not valid',
    promoSuccess: 'You are credited with {0} bonuses',
    warnComment: 'If possible, enter the entrance or leave a comment to the driver',
    ended: 'Ended',
    yourRating: 'Your rating',
    coeficientIncr: 'In high demand now',
    comfortPlace: 'Inconvenient boarding area',
    proposePlace: 'We can suggest',
    inputsPrompt: 'Indicate the entrance or leave a comment to the driver',
    blockedUser: 'Your account has been suspended. Contact the administrator at {0}',
    tripDetails: 'Trip details',
    tariff: 'Tariff',
    distInCity: 'Distance in city',
    distOutCity: 'Distance out of city',
    stayTime: 'Stay time',
    standartFare: 'Standart',
    corporateFare: 'Corporate',
    corporateConfirm: 'Confirm the corporate trip?',
    standartConfirm: 'Confirm the standart trip?',
    templateDefault: 'Template',
    driverTime: 'Arrive',
    whoOrderFor: 'Who is the order for?',
    confirmOther:
      'By confirming, the user agrees receive SMS and calls from the service, regarding this trip',
    calendarPlanned: 'Taxi ordered',
    findHistory: 'Trips were found',
    findRequest: 'At your request',
    findPick: 'Pick car type',
    today: 'Today',
    findTrips: 'Search trips',
    pastTrips: 'Past trips',
    changeRequest: 'Change search request',
    priceMinIn: 'Min. price in city',
    priceMinOut: 'Min. price out of city',
    minKmIn: 'Min. km in city',
    minKmOut: 'Min. km out of city',
    pricePerKmIn: 'Price/km in city',
    pricePerKmOut: 'Price/km out of city',
    pricePerStayMinute: 'Price/minute stay',
    pricePerTripMinute: 'Price/minute trip',
  },
  uk: {
    welcome: 'Вітаємо',
    enterPhoneNumber: 'Введіть номер телефону',
    yourPromocode: 'Ваш промо-код',
    howItsWorkNoBonus: 'Поділіться додатком і отримайте бонуси від поїздок друзів.',
    howItsWorkText:
      'Поділіться кодом {0} і отримайте {1} бонусів на рахунок. Той хто зареєструється за допомогою кода отримає {2} бонусів.',
    howItsWorkText1: 'Поділіться кодом {0} з друзями і отримайте {1} бонусів на рахунок.',
    howItsWorkText2:
      'Поділіться кодом {0} з друзями. Той хто зареєструється за допомогою кода отримає {1} бонусів.',
    howItWork: 'Як це працює?',
    refReward: 'Ви будете отримувати {0} бонусів з кожної поїздки друзів.',
    refRewardPercent: 'Ви будете отримувати {0}% з кожної поїздки друзів.',
    shareApp: 'Поширити додаток',
    appLanguage: 'Мова додатку',
    defPayment: 'Оплата за замовч.',
    defTariff: 'Тариф за замовч.',
    defTrip: 'Поїздка за замовч.',
    dontCallMe: 'Не дзвонити мені',
    showActions: 'Показувати акції',
    noticeAboutshowPriceNotification: 'Повідомляти про зниження ціни',
    logout: 'Вийти з акаунта',
    settings: 'Налаштування',
    removeAddress: 'Видалити адресу?',
    addressWasRemoved: 'Адресу буде видалено зі списку збережених',
    remove: 'Видалити',
    savedAddresses: 'Збережені адреси',
    noSavedAddresses: 'Збережені адреси відсутні',
    ifLeaveNoSave: 'Якщо закриєте це вікно - адреса не збережеться..',
    leaveWithoutSave: 'Вийти без збереження?',
    leave: 'Вийти',
    return: 'Повернутись',
    youCanFindAddress: 'Ви зможете знайти нову адресу в збережених адресах',
    addressSaved: 'Адресу збережено',
    commentDriver: 'Коментар водію',
    saveTheAddress: 'Зберегти адресу',
    name: 'Назва',
    approach: "Під'їзд",
    cash: 'Готівка',
    cashless: 'Безготівково',
    order: 'Замовити',
    newTemplate: 'Новий шаблон',
    cancel: 'Скасувати',
    canceled: 'Скасовано',
    create: 'Створити',
    warning: 'Увага!',
    previous: 'Попередні',
    planned: 'Заплановані',
    templates: 'Шаблони',
    finishYourRide: 'Завершіть поїздку перед новим викликом',
    yourHistoryEmpty: 'Історія поїздок відсутня',
    noPlannedRides: 'Заплановані поїздки відсутні',
    noSavedTemplates: 'Збережені шаблони відсутні',
    myTrips: 'Мої поїздки',
    enterYourData: 'Заповніть, будь ласка, дані, щоб вас було легше ідентифікувати',
    userName: "Ім'я",
    userEmail: 'Електронна скринька',
    userBirthday: 'Дата народження',
    myFinances: 'Мої фінанси',
    information: 'Інформація',
    feedback: 'Зворотній зв’язок',
    profile: 'Профіль',
    orderByPhone: 'Замовити по телефону',
    allowGeodata: 'Для коректної роботи додатку надайте дозвіл на отримання геоданих',
    userWrongCode: 'Невірний код підтвердження. Уважно введіть код або змініть номер.',
    changePhoneNumber: 'Змінити номер телефону',
    codeReSend: 'Повторне надсилання коду через',
    repeatRequest: 'Повторити запит',
    payWithCreditCard: 'Кредитною карткою',
    paymentMethod: 'Як краще оплатити?',
    whereToGo: 'Куди їдемо?',
    areYouHere: 'Ви тут?',
    outOfRun: 'Територія не обслуговується',
    comment: 'Коментар',
    added: 'Додано',
    add: 'Додати',
    addService: 'Дод. послуги',
    payment: 'Оплата',
    orderNow: 'Замовити зараз',
    orderLater: 'На потім',
    tripCanceled: 'Поїздку скасовано',
    tripCancelReason: 'Причини скасування',
    bonusDebit20: 'З бонусного рахунку списано 20 {0}',
    cancelConfirm: 'Ви дійсно хочете скасувати поїздку?',
    cancelReasonDriverAsked: 'Водій попросив скасувати',
    cancelReasonOrderByMistake: 'Замовив помилково',
    cancelReasonWaitToLong: 'Занадто довго чекати',
    cancelReasonUseAnotherTaxi: 'Поїхав на іншому таксі',
    cancelReasonDriverWrongWay: 'Водій поїхав не туди',
    cancelReasonEnter: 'Введіть причину',
    cancelReasonChangePlans: 'Змінились плани',
    car: 'Авто',
    trip: ' Поїздку',
    close: 'Закрити',
    startWrite: 'Почніть писати',
    save: 'Зберегти',
    startAddress: 'Адреса відправлення',
    addressOfArrival: 'Адреса прибуття',
    driverInPlace: 'Водій вже на місці',
    driver: 'Водій',
    number: 'Номер',
    color: 'Колір',
    waitNear: 'Очікуйте біля',
    imlate: 'Запізнююсь',
    comeOut: 'Виходжу',
    timeInRoad: 'Час поїздки',
    cost: 'Вартість',
    moreTaxi: 'Ще таксі',
    infoText: 'Просторі машини та водії з високими оцінками',
    infoCarsText: 'Skoda Octavia, Ford Galaxy, Hyundai та 40 інших',
    testimonials: 'Переваги',
    infoProsText: 'Просторі та зручні автомобілі',
    infoProsTolerant: 'Ввічливі та толерантні водії',
    infoProsHighRate: 'Водії з високим рейтингом',
    setComfortTime: 'Вкажіть зручний час \n подачі',
    via: 'Через',
    timeMin: 'хв',
    date: 'Дата',
    time: 'Час',
    setAlarm: 'Встановити нагадування',
    noFreeCar: 'Поруч з вами немає вільних авто',
    weCanOffer: 'Ми можемо запропонувати',
    await: 'Чекати',
    payCarOtherArea: 'Оплатити подачу авто з іншого району',
    callOtherCar: 'Викликати інше авто',
    checkOtherCarType: 'Вибрати інший клас авто',
    extraOverPay: 'Сума доплати',
    overPay: 'Доплата',
    overPayComment:
      'Примітка: Чим більшою буде доплата, тим швидше авто з іншого району зреагують на замовлення.',
    rideCost: 'Вартість поїздки',
    returnToMap: 'Повернутись до карти',
    send: 'Відправити',
    yourRideIsOver: 'Поїздку завершено',
    createNewTemplate: 'Створити шаблон поїздки',
    searchForCar: 'Шукаю таксі',
    additionally: 'Додатково',
    services: 'послуги',
    tripFrom: 'Від',
    tripTo: 'До',
    carClass: 'Клас авто',
    additionalServices: 'Додаткові послуги',
    additionalServicesList: 'Чек, Кондиціонер, Дитяче крісло, Тонування',
    orderStatus: 'Статус замовлення',
    changeAddress: 'Змінити адресу',
    filingCar: 'Подача',
    chooseCreditCard: 'Виберіть кредитну картку',
    addCreditCard: 'Додати карту',
    validTill: 'Дійсна до',
    saveCreditCard: 'Зберегти карту',
    noAddress: 'Немає адреси',
    showOnMap: 'Вказати на карті',
    noInternet: "З'єднання з інтернетом відсутнє",
    update: 'Оновити',
    confirm: 'OK',
    ok: 'OK',
    enterSendedCode: 'Введіть код надісланий на \n',
    enterValidEmail: 'Введіть правильну адресу електронної пошти!',
    about: 'Про додаток',
    license: 'Ліцензійна угода',
    privacyPolicy: 'Політика конфіденційності',
    version: 'Версія',
    hosted: 'Розміщено',
    callback: 'Зворотній зв’язок',
    message: 'Повідомлення',
    feedbackSendSuccess: 'Повідомлення успішно надіслано',
    feedbackSendError: 'Ваше повідомлення не було доставлене, спробуйте пізніше',
    locationAccessHeader: 'Нам потрібно отримати доступ до вашого місцезнаходження',
    locationAccessRequest:
      'Ми використовуємо ваше місцезнаходження, щоб показати, де ви знаходитесь на карті',
    selectPhoto: 'Виберіть фото',
    servicesTravelTrunk: 'Порожній багажник',
    servicesTinted: 'Тонування',
    servicesConditioner: 'Кондиціонер',
    servicesTerminal: 'Термінал',
    servicesAnimals: 'Перевезення тварин',
    servicesChildSeat: 'Дитяче крісло',
    servicesLowLanding: 'Низька посадка',
    servicesReceipt: 'Чек',
    chooseAdditionalServices: 'Виберіть\n додаткові послуги',
    servicesTripToFriend: 'Поїздка другу',
    costOfTariff: 'вартості тарифу',
    chat: 'Чат',
    onQuitPress: 'Для виходу двічі натисніть "Назад"',
    statusSearching: 'Пошук',
    statusAwaiting: 'Прийнятий',
    statusDriveOnPlace: 'Водій на місці',
    statusInTheWay: 'В дорозі',
    ratingBadCar: 'Брудна машина чи машина погано пахне',
    ratingLongRide: 'Вибрав поганий маршрут чи пропустив поворот',
    ratingLowSpeed: 'Їхав занадто повільно',
    ratingTrafficRules: 'Порушував правила дорожнього руху',
    ratingManyTalks: 'Багато розмовляв',
    ratingClientFeelBad: 'Вів машину так, що клієнту стало погано',
    ratingRideOnOtherCar: 'Приїхав на машині, яка не відповідала вимогам замовлення',
    ratingRefuseHelpWithLuggage: 'Відмовився допомогти завантажити багаж',
    ratingAskedForGoodScore: 'Попросив поставити хорошу оцінку',
    ratingCallWithoutReason: 'Дзвонив без необхідності',
    ratingWhyBadRating: 'Чому погана оцінка?',
    rateTerribly: 'Жахливо',
    rateBadly: 'Погано',
    rateSatisfactorily: 'Задовільно',
    rateGood: 'Добре',
    ratePerfectly: 'Відмінно',
    rateARide: 'Оцініть поїздку',
    taxiNotFound: ' Таксі не знайдено',
    saved: 'Збережені',
    popular: 'Популярні',
    nearest: 'Найближчі',
    secondAddressDidntSet:
      'Ви не вказали кінцеву адресу, через це пошук машини може тривати довше.',
    result: 'Результат',
    transactionCompleted: 'Транзакція виконана успішно',
    addCreditCardRequired: 'Необхідно додати кредитну картку',
    distance: 'Відстань',
    timeArrive: 'Час прибуття',
    deleteCardConfirm: 'Видалити картку?',
    noCreditCard: 'Збережені картки відсутні',
    address: 'Адреса',
    feedbackInfo: 'Напишіть скаргу або пропозицію',
    map: 'Карта',
    permissionDeniedTitle: 'Доступ не надано',
    permissionDeniedText:
      'Доступ потрібний для отримання знімків з камери та вибору фото з галереї.',
    permissionDeniedRetry: 'Повторити',
    permissionDeniedSure: 'Я впевнений',
    enterCode: 'Введи код',
    checkCode: 'Уважно перевірте код, після реєстрації його буде неможливо змінити',
    promoInput: 'Якщо у вас є промо код, натисніть сюди',
    promo: 'Ваш промо-код',
    creditCard: 'Карткою',
    agree1: 'Продовжуючи, ви погоджуєтеся з ',
    agree2: 'ліцензійними умовами ',
    agree3: 'та ',
    agree4: 'політикою конфіденційності',
    loginLink1: 'Для відображення інформації',
    loginLink2: 'увійдіть до свого облікового запису',
    pass: 'Пропустити',
    invalidCard: 'Номер кредитної карти не вірний',
    invalidMonth: 'Невірний місяць закінчення терміну картки',
    invalidYear: 'Невірний рік закінчення терміну картки ',
    invalidDate: 'Дата закінчення терміну картки не вірна',
    invalidCvv: 'Невірний CVV',
    cardDecline: 'Карту відхилено',
    error: 'Помилка',
    takePhoto: 'Зробити фото',
    chooseFromLibrary: 'Обрати з Галереї',
    km: 'км.',
    m: 'м.',
    deleteTripConfirm: 'Ви впевнені, що хочеш видалити поїздку з історії?',
    deleteTemplateConfirm: 'Ви впевнені, що хочеш видалити шаблон?',
    onAccount: 'У вас на рахунку',
    bonuses: 'бонусів',
    bonusPay: 'Бонусами',
    amountBonuses: 'Кількість бонусів',
    bonusLimit: 'Перевищено максимально можливе значення бонусів - ',
    bonusLow: 'У вас не вистачає бонусів',
    bonusZero: 'Введіть число більше 0',
    serviceCount: 'Послуг:',
    offerSurcharge: 'Запропонувати доплату',
    shareText: 'Встановіть додаток {0} і отримайте нагороду по промокоду {1}\n{2}',
    shareTrip1: 'Замовив таксі через додаток',
    shareTrip2: 'їду по маршруту',
    lateTime: 'На скільки хвилин?',
    change: 'Змінити',
    activeTrips: 'Активні поїздки',
    preordered: 'Передзамовлено',
    reserved: 'Зарезервовано',
    search: 'Пошук',
    noContacts: 'Контактів не знайдено',
    noActiveTrips: 'Активні поїздки відсутні',
    addNumber: 'Додати номер',
    points: 'точки',
    bonusesTab: 'Мої бонуси',
    myCards: 'Мої карти',
    usePromo: 'Використати',
    enterPromo: 'Введіть промокод',
    aboutPromo: 'Промокод надає змогу отримати бонуси для поїздки',
    promoFail: 'Промокод не дійсний',
    promoSuccess: 'Вам нараховано {0} бонусів',
    warnComment: "Якщо можливо, вкажіть під'їзд або залишіть коментар водію",
    ended: 'Виконано',
    yourRating: 'Ваша оцінка',
    coeficientIncr: 'Зараз має високий попит',
    comfortPlace: 'Незручне місце посадки',
    proposePlace: 'Ми можемо запропонувати',
    inputsPrompt: "Вкажіть під'їзд або залиште коментар для водія",
    blockedUser: "Ваш обліковий запис заблокований. Зв'яжіться з адміністратором по номеру {0}",
    tripDetails: 'Деталі поїздки',
    tariff: 'Тариф',
    distInCity: 'Відстань по місту',
    distOutCity: 'Відстань за містом',
    standartFare: 'Стандартна',
    corporateFare: 'Корпоративна',
    corporateConfirm: 'Підтверджуєте коропоративну поїздку?',
    standartConfirm: 'Підтверджуєте стандартну поїздку?',
    stayTime: 'Час простою',
    templateDefault: 'Шаблон',
    driverTime: 'Водій прибуде',
    whoOrderFor: 'Для кого замовлення?',
    confirmOther:
      'Підтверджуючи, користувач дає згоду приймати СМС та дзвінки від служби, відносно цієї поїздки',
    calendarPlanned: 'Поїздка на таксі',
    findHistory: 'Знайдено поїздок',
    findRequest: 'По твоєму запиту',
    findPick: 'Виберіть клас авто',
    today: 'Сьогодні',
    findTrips: 'Знайти поїздку',
    pastTrips: 'Минулі поїздки',
    changeRequest: 'Змінити пошук',
    priceMinIn: 'Мін. ціна в місті',
    priceMinOut: 'Мін. ціна за містом',
    minKmIn: 'Мін. км в місті',
    minKmOut: 'Мін. км за містом',
    pricePerKmIn: 'Ціна/км в місті',
    pricePerKmOut: 'Ціна/км за містом',
    pricePerStayMinute: 'Ціна/хв простою',
    pricePerTripMinute: 'Ціна/хв поїздки',
  },
  ru: {
    welcome: 'Приветствие',
    enterPhoneNumber: 'Введите номер телефона',
    yourPromocode: 'Ваш промо-код',
    howItsWorkNoBonus: 'Поделитесь приложением и получайте бонусы от поездок друзей.',
    howItsWorkText:
      'Поделитесь кодом {0} с друзьями и получите {1} бонусов на счет. Тот кто зарегистрируется по этому коду получит {2} бонусов.',
    howItsWorkText1: 'Поделитесь кодом {0} с друзьями и получите {1} бонусов на счет.',
    howItsWorkText2:
      'Поделитесь кодом {0} c друзьями. Тот кто зарегистрируется по этому коду получит {1} бонусов.',
    howItWork: 'Как это работает?',
    refReward: 'Вы будете получать {0} бонусов с каждой поездки друзей.',
    refRewardPercent: 'Вы будете получать {0}% с каждой поездки друзей.',
    shareApp: 'Поделиться приложением',
    appLanguage: 'Язык приложения',
    defPayment: 'Оплата по умолч.',
    defTariff: 'Тариф по умолч.',
    defTrip: 'Поездка по умолч.',
    dontCallMe: 'Не звонить мне',
    showActions: 'Показывать акции',
    noticeAboutshowPriceNotification: 'Сообщать про снижение цены',
    logout: 'Выйти c аккаунта',
    settings: 'Настройки',
    removeAddress: 'Удалить адрес?',
    addressWasRemoved: 'Адрес будет удален из списка сохраненных',
    remove: 'Удалить',
    savedAddresses: 'Сохраненные адреса',
    noSavedAddresses: 'Сохраненные адреса отсутствуют',
    ifLeaveNoSave: 'Если закроете это окно - адрес не сохранится.',
    leaveWithoutSave: 'Выйти без сохранения?',
    leave: 'Выйти',
    return: 'Вернуться',
    youCanFindAddress: 'Вы сможете найти новый адрес в сохраненных адресах.',
    addressSaved: 'Адрес сохранен',
    commentDriver: 'Комментарий водителю',
    saveTheAddress: 'Сохранить адрес',
    name: 'Название',
    approach: 'Подъезд',
    cash: 'Наличные',
    cashless: 'Безналичный',
    order: 'Заказать',
    newTemplate: 'Новый шаблон',
    cancel: 'Отменить',
    canceled: 'Отменено',
    create: 'Создать',
    warning: 'Внимание!',
    previous: 'Предыдущие',
    planned: 'Запланированные',
    templates: 'Шаблоны',
    finishYourRide: 'Завершите поездку перед новым вызовом',
    yourHistoryEmpty: 'История поездок отсутствует',
    noPlannedRides: 'Запланированные поездки отсутствуют',
    noSavedTemplates: 'Сохраненные шаблоны отсутствуют',
    myTrips: 'Мои поездки',
    enterYourData: 'Пожалуйста, заполните данные, чтобы облегчить вашу идентификацию',
    userName: 'Имя',
    userEmail: 'Электронная почта',
    userBirthday: 'Дата рождения',
    myFinances: 'Мои финансы',
    information: 'Информация',
    feedback: 'Обратная связь',
    profile: 'Профиль',
    orderByPhone: 'Заказать по телефону',
    allowGeodata: 'Для корректной работы приложения предоставьте разрешение на получение геоданных',
    userWrongCode: 'Неверный код подтверждения. Внимательно введите код или измените номер',
    changePhoneNumber: 'Изменить номер телефона',
    codeReSend: 'Повторная отправка кода через',
    repeatRequest: 'Повторить запрос',
    payWithCreditCard: 'Кредитной картой',
    paymentMethod: 'Как лучше оплатить?',
    whereToGo: 'Куда едем?',
    areYouHere: 'Вы тут?',
    outOfRun: 'Территория не обслуживается',
    comment: 'Коммент.',
    added: 'Добавлено',
    add: 'Добавить',
    addService: 'Доп. услуги',
    payment: 'Оплата',
    orderNow: 'Заказать сейчас',
    orderLater: 'На потом',
    tripCanceled: 'Поездку отменено',
    tripCancelReason: 'Причины отмены',
    bonusDebit20: 'С бонусного счета списано 20 {0}',
    cancelConfirm: 'Вы действительно хотите отменить поездку?',
    cancelReasonDriverAsked: 'Водитель попросил отменить',
    cancelReasonOrderByMistake: 'Заказал ошибочно',
    cancelReasonWaitToLong: 'Слишком долго ждать',
    cancelReasonUseAnotherTaxi: 'Уехал на другом такси',
    cancelReasonDriverWrongWay: 'Водитель поехал не туда',
    cancelReasonEnter: 'Введите причину',
    cancelReasonChangePlans: 'Изменились планы',
    car: 'Авто',
    trip: ' Поездку',
    close: 'Закрыть',
    startWrite: 'Начните писать',
    save: 'Сохранить',
    startAddress: 'Адрес отправления',
    addressOfArrival: 'Адрес прибытия',
    driverInPlace: 'Водитель уже на месте',
    driver: 'Водитель',
    number: 'Номер',
    color: 'Цвет',
    waitNear: 'Ожидайте возле',
    imlate: 'Опаздываю',
    comeOut: 'Выхожу',
    timeInRoad: 'Время в пути',
    cost: 'Стоимость',
    moreTaxi: 'Еще такси',
    infoText: 'Просторные машины и водители с высокими оценками',
    infoCarsText: 'Skoda Octavia, Ford Galaxy, Hyundai и 40 других',
    testimonials: 'Преимущества',
    infoProsText: 'Просторные и удобные автомобили',
    infoProsTolerant: 'Вежливые и толерантны водители',
    infoProsHighRate: 'Водители с высоким рейтингом',
    setComfortTime: 'Укажите удобное время \nподачи',
    via: 'Через',
    timeMin: 'мин',
    date: 'Дата',
    time: 'Время',
    setAlarm: 'Установить напоминание',
    noFreeCar: 'Рядом с вами нет свободных авто',
    weCanOffer: 'Мы можем предложить',
    await: 'Ожидать',
    payCarOtherArea: 'Оплатить подачу авто из другого района',
    callOtherCar: 'Вызвать другое авто',
    checkOtherCarType: 'Выбрать другой класс авто',
    extraOverPay: 'Сумма доплаты',
    overPay: 'Доплата',
    overPayComment:
      'Примечание: Чем больше будет доплата, тем быстрее авто из другого района отреагируют на заказ.',
    rideCost: 'Стоимость поездки',
    returnToMap: 'Вернуться к карте',
    send: 'Отправить',
    yourRideIsOver: 'Поездку завершено',
    createNewTemplate: 'Создать шаблон поездки',
    searchForCar: 'Ищу такси',
    additionally: 'Дополнительно',
    services: 'услуги',
    tripFrom: 'От',
    tripTo: 'До',
    carClass: 'Класс авто',
    additionalServices: 'Дополнительные услуги',
    additionalServicesList: 'Чек, Кондиционер, Детское кресло, Тонировка',
    orderStatus: 'Статус заказа',
    changeAddress: 'Изменить адрес',
    filingCar: 'Подача',
    chooseCreditCard: 'Выберите кредитную карту',
    addCreditCard: 'Добавить карту',
    validTill: 'Годна до',
    saveCreditCard: 'Сохранить карту',
    noAddress: 'Адрес не указан ',
    showOnMap: 'Указать на карте',
    noInternet: 'Соединение с интернетом отсутствует',
    update: 'Обновить',
    confirm: 'OK',
    ok: 'OK',
    enterSendedCode: 'Введите код отправленный на\n',
    enterValidEmail: 'Введите правильный адрес электронной почты',
    about: 'О приложении',
    license: 'Лицензионное соглашение',
    privacyPolicy: 'Политика Конфиденциальности',
    version: 'Версия',
    hosted: 'Размещено',
    callback: 'Обратная связь',
    message: 'Сообщение',
    feedbackSendSuccess: 'Сообщение успешно отправлено',
    feedbackSendError: 'Сообщение не доставлено, попробуйте позже',
    locationAccessHeader: 'Нам нужно получить доступ к вашему местоположению',
    locationAccessRequest:
      'Мы используем ваше местоположение, чтобы показать, где вы находитесь на карте',
    selectPhoto: 'Выберите фото',
    servicesTravelTrunk: 'Пуcтой багажник',
    servicesTinted: 'Тонирование',
    servicesConditioner: 'Кондиционер',
    servicesTerminal: 'Терминал',
    servicesAnimals: 'Перевозка животных',
    servicesChildSeat: 'Детское кресло',
    servicesLowLanding: 'Низкая посадка',
    servicesReceipt: 'Чек',
    chooseAdditionalServices: 'Выберите\n дополнительные услуги',
    servicesTripToFriend: 'Поездка другу',
    costOfTariff: 'стоимости тарифа',
    chat: 'Чат',
    onQuitPress: 'Для выхода дважды нажмите "Назад"',
    statusSearching: 'Поиск',
    statusAwaiting: 'Принятый',
    statusDriveOnPlace: 'Водитель на месте',
    statusInTheWay: 'В дороге',
    ratingBadCar: 'Грязная или неприятно пахнущая машина',
    ratingLongRide: 'Выбрал длинный маршрут или пропустил поворот',
    ratingLowSpeed: 'Ехал слишком медленно',
    ratingTrafficRules: 'Нарушал правила дорожного движения',
    ratingManyTalks: 'Много разговаривал',
    ratingClientFeelBad: 'Вел машину так, что клиенту стало плохо',
    ratingRideOnOtherCar: 'Приехал на машине, не соответствующей требованиям заказа',
    ratingRefuseHelpWithLuggage: 'Отказался помочь погрузить багаж',
    ratingAskedForGoodScore: 'Попросил поставить хорошую оценку',
    ratingCallWithoutReason: 'Звонил без необходимости',
    ratingWhyBadRating: 'Почему плохая оценка?',
    rateTerribly: 'Ужасно',
    rateBadly: 'Плохо',
    rateSatisfactorily: 'Удовлетворительно',
    rateGood: 'Хорошо',
    ratePerfectly: 'Отличнo',
    rateARide: 'Оцените поезку',
    taxiNotFound: 'Такси не найдено',
    saved: 'Сохраненные',
    popular: 'Популярные',
    nearest: 'Ближайшие',
    secondAddressDidntSet:
      'Вы не указали второй адрес, из-за этого поиск машины может длиться дольше.',
    result: 'Результат',
    transactionCompleted: 'Транзакция завершена успешно',
    addCreditCardRequired: 'Необходимо добавить кредитную карту',
    distance: 'Расстояние',
    timeArrive: 'Время прибытия',
    deleteCardConfirm: 'Удалить карту?',
    noCreditCard: 'Сохраненные карты отсутствуют',
    address: 'Адрес',
    feedbackInfo: 'Напишите жалобу или пожелание',
    map: 'Карта',
    permissionDeniedTitle: 'Доступ отклонен',
    permissionDeniedText:
      'Доступ нужен для выбора изображения из галереи или для получения снимка с камеры',
    permissionDeniedRetry: 'повторить',
    permissionDeniedSure: 'Я уверен',
    enterCode: 'Введи код',
    checkCode: 'Внимательно проверьте код, после регистрации его будет невозможно изменить',
    promoInput: 'Если у вас есть промо код - нажмите сюда',
    promo: 'Ваш промо-код',
    creditCard: 'Картой',
    agree1: 'Продолжая, вы соглашаетесь с ',
    agree2: 'лицензионными условиями ',
    agree3: 'и ',
    agree4: 'политикой конфиденциальности',
    loginLink1: 'Для отображения информации',
    loginLink2: 'войдите в свою учетную запись',
    pass: 'Пропустить',
    invalidCard: 'Неверный номер кредитной карты',
    invalidMonth: 'Месяц окончания термина карты не верный',
    invalidYear: 'Неверный год окончания срока карты ',
    invalidDate: 'Дата окончания срока карты не верная',
    invalidCvv: 'Неверный CVV',
    cardDecline: 'Карта отклонена',
    error: 'Ошибка',
    takePhoto: 'Сделать фото...',
    chooseFromLibrary: 'Выбрать из Галереи...',
    km: 'км.',
    m: 'м.',
    deleteTripConfirm: 'Вы уверены, что хотите удалить поездку из истории?',
    deleteTemplateConfirm: 'Вы уверены, что хотите удалить шаблон?',
    onAccount: 'На вашем счету',
    bonuses: 'бонусов',
    bonusPay: 'Бонусами',
    amountBonuses: 'Количество бонусов',
    bonusLimit: 'Превышено максимально возможное значение бонусов - ',
    bonusLow: 'У вас не хватает бонусов',
    bonusZero: 'Введите число больше 0',
    serviceCount: 'Услуг:',
    offerSurcharge: 'Предложить доплату',
    shareText: 'Скачайте приложение {0} и получите награду по промокоду {1}\n{2}',
    shareTrip1: 'Заказал такси через приложение',
    shareTrip2: 'еду по маршруту',
    lateTime: 'На сколько минут?',
    change: 'Изменить',
    activeTrips: 'Активные поездки',
    preordered: 'Предзаказано',
    reserved: 'Зарезервировано',
    search: 'Поиск',
    noContacts: 'Контактов не найдено',
    noActiveTrips: 'Активные поездки отсутствуют',
    addNumber: 'Добавить номер',
    points: 'точки',
    bonusesTab: 'Мои бонусы',
    myCards: 'Мои карты',
    usePromo: 'Использовать',
    enterPromo: 'Введите промокод',
    aboutPromo: 'Промокод дает возможность получить бонусы для поездки',
    promoFail: 'Промокод не действителен',
    promoSuccess: 'Вам насчитано {0} бонусов',
    warnComment: 'Якщо возможно, укажите подъезд или оставьте комментарий водителю',
    ended: 'Завершено',
    yourRating: 'Ваша оценка',
    coeficientIncr: 'Пользуется высоким спросом',
    comfortPlace: 'Неудобная зона посадки',
    proposePlace: 'Мы можем предложить',
    inputsPrompt: 'Укажите подъезд или оставьте комментарий водителю',
    blockedUser: 'Ваша учетная запись заблокирована. Свяжитесь с администратором по номеру {0}',
    tariff: 'Тариф',
    tripDetails: 'Детали поездки',
    distInCity: 'Расст. по городу',
    distOutCity: 'Расст. вне города',
    stayTime: 'Время простоя',
    standartFare: 'Стандартная',
    corporateFare: 'Корпоративная',
    corporateConfirm: 'Подтверждаете корпоративную поездку?',
    standartConfirm: 'Подтверждаете стандартную поездку?',
    templateDefault: 'Шаблон',
    driverTime: 'Водитель приедет',
    whoOrderFor: 'Для кого заказ?',
    confirmOther:
      'Подтверждая, пользователь дает согласие принимать СМС и звонки от службы, относительно этой поездки',
    calendarPlanned: 'Поездка на такси',
    findHistory: 'Найдено поездок',
    findRequest: 'По твоему запросу',
    findPick: 'Выберите класс авто',
    today: 'Сегодня',
    findTrips: 'Найти поездку',
    pastTrips: 'Прошлые поездки',
    changeRequest: 'Изменить поиск',
    priceMinIn: 'Мин. цена в городе',
    priceMinOut: 'Мин. цена за городом',
    minKmIn: 'Мин. км в городе',
    minKmOut: 'Мин. км за городом',
    pricePerKmIn: 'Цена/км в городе',
    pricePerKmOut: 'Цена/км за городом',
    pricePerStayMinute: 'Цена/мин простоя',
    pricePerTripMinute: 'Цена/мин поездки',
  },
  sk: {
    welcome: 'Vitajte',
    enterPhoneNumber: 'Zadajte telefónne číslo',
    giveFriendDiscount:
      '???Present a friend with a discount {0} {1} for the first six trips. For new users only.',
    yourPromocode: '???Your promo code',
    howItsWork: '???How does it work?',
    howItsWorkText:
      '???Share code {0} with friends and get {1} bonuses on your account. Person registered with the code gets {2} bonuses.',
    howItsWorkText1: '???Share code {0} with friends and get {1} bonuses on your account.',
    howItsWorkText2:
      '???Share code {0} with friends. Person registered with the code gets {1} bonuses.',
    howItsWorkNoBonus: '???Share app and get bonuses from your friends trips.',
    howItWork: 'Ako to funguje?',
    refReward: "???You will get {0} bonuses from every friend's trip.",
    refRewardPercent: "???You will get {0}% from every friend's trip.",
    share: 'Zdieľať',
    shareApp: 'Zdieľať aplikáciu',
    appLanguage: 'Jazyk',
    defPayment: 'Predvolený spôsob platby',
    defTariff: 'Predvolená tarifa',
    defTrip: 'Predvolený typ jazdy',
    dontCallMe: 'Nevolajte mi',
    showActions: 'Ukazovať špeciálne ponuky',
    noticeAboutshowPriceNotification: 'Informujte ma o poklese cien',
    logout: 'Odhlásiť sa',
    settings: 'Nastavenia',
    removeAddress: 'Odstrániť adresu?',
    addressWasRemoved: 'Adresa bola bola odstránená z Uložených',
    remove: 'Odstrániť',
    savedAddresses: 'Uložené adresy',
    noSavedAddresses: 'Nemáte uložené žiadne adresy',
    ifLeaveNoSave: 'Ak zatvoríte okno adresa nebude uložená',
    leaveWithoutSave: 'Ukončiť bez uloženia zmien?',
    leave: 'Ukončiť',
    return: 'Späť',
    youCanFindAddress: 'Novú adresu nájdete medzi Uložených.',
    addressSaved: 'Adresa bola uložená',
    commentDriver: 'Správa pre vodiča',
    saveTheAddress: 'Uložiť adresu',
    name: 'Názov',
    approach: 'Vchod',
    cash: 'Hotovosť',
    cashless: 'Karta',
    order: 'Objednať',
    newTemplate: 'Nová šablóna',
    cancel: 'Zrušiť',
    canceled: 'Zrušené',
    create: 'Vytvoriť',
    warning: 'Pozor!',
    previous: 'Predchádzajúce',
    planned: 'Plánované',
    templates: 'Šablóny',
    finishYourRide: 'Dokončite cestu pred novou objednávkou',
    yourHistoryEmpty: 'Žiadne predchádzajúce cesty',
    noPlannedRides: 'Žiadne plánované cesty',
    noSavedTemplates: 'Žiadne uložené šablóny',
    myTrips: 'Moje cesty',
    enterYourData: '???Please fill in details for faster identification',
    userName: '???Name',
    userEmail: '???Email',
    userBirthday: '???Birthday',
    myFinances: '???My finances',
    information: '???Information',
    feedback: '???Feedback',
    profile: 'Profil',
    orderByPhone: 'Objednať telefonicky',
    allowGeodata: 'Povoliť prístup k vašej polohe pre správne fungovanie aplikácie',
    userWrongCode: 'Nesprávny kód. Skontrolujte kód alebo zadajte iné číslo.',
    changePhoneNumber: 'Zmeniť telefónne číslo',
    codeReSend: 'Nový kód dostanete za',
    repeatRequest: 'Opakovať',
    payWithCreditCard: 'Debetnou kartou',
    paymentMethod: 'Preferovaný spôsob platby?',
    whereToGo: 'Kam ideme?',
    areYouHere: 'Vy ste tu?',
    outOfRun: 'Územie nie je obsluhované',
    comment: 'Komentár',
    added: 'Pridané',
    add: 'Pridať',
    addService: 'Doplnkové služby',
    payment: 'Platba',
    orderNow: 'Objednať ihneď',
    orderLater: 'Neskôr',
    tripCanceled: 'Cesta zrušená',
    tripCancelReason: 'Dôvod zrušenia',
    bonusDebit20: '20 {0} odpočítané z vášho bonusového účtu',
    cancelConfirm: 'Naozaj chcete zrušiť cestu?',
    cancelReasonDriverAsked: 'Vodič požiadal o zrušenie',
    cancelReasonOrderByMistake: 'Omylom objednané',
    cancelReasonWaitToLong: 'Príliš dlho čakať',
    cancelReasonUseAnotherTaxi: 'Použil iné taxi',
    cancelReasonDriverWrongWay: 'Vodič išiel zlou cestou',
    cancelReasonEnter: 'Uveďte dôvod',
    cancelReasonChangePlans: 'Plány zlyhali',
    car: 'Auto',
    trip: 'Cesta',
    close: 'Zavrieť',
    startWrite: 'Začnite písať',
    save: 'Uložiť',
    startAddress: 'Adresa na vyzdvihnutie',
    addressOfArrival: 'Cieľová adresa',
    driverInPlace: 'Vodič dorazil',
    driver: 'Vodič',
    number: 'ŠPZ',
    color: 'Farba',
    waitNear: 'Počkajte blízko',
    imlate: 'Meškám',
    comeOut: 'Idem',
    timeInRoad: 'Čas na ceste',
    cost: 'Cena',
    moreTaxi: 'Ďalšie taxi',
    infoText: '???Spacious cars and high-rated drivers',
    infoCarsText: '???Skoda Octavia, Ford Galaxy, Hyundai and 40 other',
    testimonials: 'Výhody',
    infoProsText: '???Spacious and comfortable cars',
    infoProsTolerant: '???Polite and tolerant drivers',
    infoProsHighRate: '???High-rated drivers',
    setComfortTime: 'Uveďte vhodný \nčas na vyzdvihnutie,',
    via: 'Za',
    timeMin: 'min',
    date: 'Dátum',
    time: 'Čas',
    setAlarm: 'Nastaviť budík',
    noFreeCar: 'V blízkosti nie sú žiadne voľné autá',
    weCanOffer: 'Môžeme ponúknuť',
    await: 'Čakať',
    payCarOtherArea: 'Zaplatiť auto z iného mesta',
    callOtherCar: 'Vyžiadať si iné auto',
    checkOtherCarType: 'Zvoliť auto inej triedy',
    extraOverPay: 'Suma príplatku',
    overPay: 'Príplatok',
    overPayComment:
      'Poznámka: Vyšší príplatok vedie k rýchlejšej reakcii vozidiel z iných oblastí.',
    rideCost: 'Cena cesty',
    returnToMap: 'Späť na mapu',
    send: 'Poslať',
    yourRideIsOver: 'Vaša cesta je dokončená',
    createNewTemplate: 'Vytvoriť šablónu cesty',
    searchForCar: 'Hľadáme taxi',
    additionally: 'Navyše',
    services: 'Služby',
    tripFrom: 'Odkiaľ',
    tripTo: 'Kam',
    carClass: 'Trieda auta',
    additionalServices: 'Doplnkové služby',
    additionalServicesList: '???Check, Air Conditioning, Child seat, Tinting',
    orderStatus: 'Stav objednávky',
    changeAddress: 'Zmeniť adresu',
    filingCar: 'Príchod',
    chooseCreditCard: 'Vyberte kartu',
    addCreditCard: 'Pridať kartu',
    validTill: 'Platnosť karty',
    saveCreditCard: 'Uložiť kartu',
    noAddress: 'Žiadna adresa',
    showOnMap: 'Ukázať na mape',
    noInternet: 'Žiadne internetové pripojenie',
    update: 'Aktualizovať',
    confirm: 'OK',
    ok: 'OK',
    enterSendedCode: 'Zadajte kód odoslaný na\n',
    enterValidEmail: 'Zadajte platný e-mail',
    about: 'O aplikácii',
    license: 'Licenčná zmluva',
    privacyPolicy: 'Ochrana osobných údajov',
    version: 'Verzia',
    hosted: 'Umiestnené',
    callback: 'Spätná väzba',
    message: 'Správa',
    feedbackSendSuccess: 'Správa bola úspešne odoslaná',
    feedbackSendError: 'Správa nie je doručená, skúste neskôr',
    locationAccessHeader: 'Potrebujeme prístup k vašej polohe',
    locationAccessRequest: 'Pomocou vašej polohy zobrazujeme, kde sa nachádzate na mape',
    selectPhoto: 'Vyberte fotografiu',
    servicesTravelTrunk: 'Prázdny kufor',
    servicesTinted: 'Tónované skla',
    servicesConditioner: 'Klimatizácia',
    servicesTerminal: 'Platobný terminál',
    servicesAnimals: 'Preprava zvierat',
    servicesChildSeat: 'Detská sedačka',
    servicesLowLanding: '???Low rider',
    servicesReceipt: '???Receipt',
    chooseAdditionalServices: 'Vyberte si\n Doplnkové služby',
    servicesTripToFriend: 'Pôjde niekto iný',
    costOfTariff: '??? of tariff cost',
    chat: 'Chat',
    onQuitPress: 'Ak chcete ukončiť program, dvakrát kliknite na tlačidlo Späť.',
    statusSearching: 'Vyhľadávanie',
    statusAwaiting: 'Prijaté',
    statusDriveOnPlace: 'Vodič dorazil',
    statusInTheWay: 'Na ceste',
    ratingBadCar: 'Špinavé auto',
    ratingLongRide: 'Vybral zlú trasu alebo vynechal odbočku',
    ratingLowSpeed: 'Jazdil príliš pomaly',
    ratingTrafficRules: 'Porušoval pravidlá premávky',
    ratingManyTalks: 'Veľa rozpraval',
    ratingClientFeelBad: 'Jazda autom spôsobila klientovu nevoľnosť',
    ratingRideOnOtherCar: 'Auto nespĺňalo požiadavky',
    ratingRefuseHelpWithLuggage: 'Vodič odmietal pomôcť s nákladom batožiny',
    ratingAskedForGoodScore: '???Asked for high rates',
    ratingCallWithoutReason: '???Called unnecessarily',
    ratingWhyBadRating: '???Reasons for low rates?',
    rateTerribly: 'Otrasne',
    rateBadly: 'Zle',
    rateSatisfactorily: 'OK',
    rateGood: 'Dobre',
    ratePerfectly: 'Vyborne',
    rateARide: 'Ohodnoťte cestu',
    taxiNotFound: 'Taxi nebolo nájdené',
    saved: 'Uložené',
    popular: 'Populárne',
    nearest: 'Najbližší',
    secondAddressDidntSet: 'Neuviedli ste cieľovú adresu. Hľadanie auta môže trvať dlhšie.',
    result: 'Výsledok',
    transactionCompleted: 'Transakcia bola úspešne dokončená',
    addCreditCardRequired: 'Vyžaduje sa karta',
    distance: 'Vzdialenosť',
    timeArrive: 'Čas príchodu',
    deleteCardConfirm: 'Vymazať kartu?',
    noCreditCard: 'Žiadne uložené karty',
    address: 'Adresa',
    feedbackInfo: 'Napíšte svoje želania alebo sťažnosti',
    map: 'Mapa',
    permissionDeniedTitle: 'Prístup zamietnutý',
    permissionDeniedText: 'Potrebujeme prístup na príjem obrázkov z kamery alebo foto.',
    permissionDeniedRetry: 'Skúsiť znova',
    permissionDeniedSure: 'Som si istý',
    enterCode: 'Zadajte kód',
    checkCode: 'Prosím, starostlivo skontrolujte svoj kód, po registrácii ho nemôžete zmeniť',
    promoInput: 'Ak máte promo kód, stlačte tu',
    promo: 'Váš promo kód je',
    creditCard: 'Karta',
    agree1: 'Pokračovaním súhlasíte s ',
    agree2: 'licenčnými podmienkami ',
    agree3: 'a ',
    agree4: 'ochranou osobných údajov',
    loginLink1: 'Pre zobrazenie informácií',
    loginLink2: 'prihláste sa do svojho účtu',
    pass: 'Preskočiť',
    invalidCard: 'Nesprávne číslo kreditnej karty',
    invalidMonth: 'Neplatný mesiac platnosti karty',
    invalidYear: 'Neplatný rok platnosti karty',
    invalidDate: 'Neplatný datum platnosti karty',
    invalidCvv: 'Neplatný CVV',
    cardDecline: 'Karta bola odmietnutá',
    error: 'Chyba',
    takePhoto: 'Odfotiť',
    chooseFromLibrary: 'Vyberte si z foto',
    km: 'km.',
    m: 'm.',
    deleteTripConfirm: 'Naozaj chcete odstrániť cestu z predchádzajúcej?',
    deleteTemplateConfirm: 'Naozaj chcete odstrániť šablónu?',
    onAccount: 'Na vašom účte',
    bonuses: 'bonusy',
    bonusPay: 'Bonusy',
    amountBonuses: 'Počet bonusov',
    bonusLimit: 'Prekročená maximálna hodnota bonusov',
    bonusLow: 'Nemáte dostatok bonusov',
    bonusZero: 'Zadajte číslo väčšie ako 0',
    serviceCount: 'Služby:',
    offerSurcharge: 'Ponúknuť príplatok',
    shareText: 'Stiahnite si aplikáciu {0} a získajte odmenu za promo kód {1}\n{2}',
    shareTrip1: 'Objednať taxi pomocou aplikácie',
    shareTrip2: 'Idem cestou',
    lateTime: 'Ako dlho?',
    change: 'Zmena',
    activeTrips: 'Aktívne cesty',
    preordered: 'Predobjednané',
    reserved: 'Rezervované',
    search: 'Vyhľadávanie',
    noContacts: 'Nenašli sa žiadne kontakty',
    noActiveTrips: 'Nemáte žiadne aktívne cesty',
    addNumber: 'Pridať telefónne číslo',
    points: 'body',
    bonusesTab: 'Moje bonusy',
    myCards: 'Moje karty',
    usePromo: 'Použiť',
    enterPromo: 'Zadať promo kód',
    aboutPromo: 'Promo kód vám umožňuje získať bonusy za vaše cesty',
    promoFail: 'Promo kód nie je platný',
    promoSuccess: 'Dostávate {0} bonusov',
    warnComment: 'Ak je to možné, zadajte vchod alebo zanechajte komentár vodičovi',
    ended: 'Ukončené',
    yourRating: 'Vaše hodnotenie',
    coeficientIncr: 'Zvýšený koeficient',
    comfortPlace: 'Nevhodný nástupný priestor',
    proposePlace: 'Môžeme to navrhnúť',
    inputsPrompt: 'Zadajte vchod alebo zanechajte komentár vodičovi',
    blockedUser: 'Váš účet bol pozastavený. Kontaktujte správcu na adrese {0}',
    tripDetails: 'Podrobnosti cesty',
    tariff: 'Tarifa',
    distInCity: 'Vzdialenosť v meste',
    distOutCity: 'Vzdialenosť mimo mesta',
    stayTime: 'Čakacia doba',
    standartFare: 'Súkromná',
    corporateFare: 'Firemná',
    corporateConfirm: 'Potvrďte firemnú cestu?',
    standartConfirm: 'Potvrďte súkromnú cestu?',
    templateDefault: 'Šablóna',
    driverTime: 'Vodič dorazí',
    whoOrderFor: 'Pre koho je určená objednávka?',
    confirmOther:
      'Potvrdením súhlasí užívateľ s prijímaním SMS a hovorov zo služby týkajúcich sa tejto cesty',
    calendarPlanned: 'Taxi objednané',
    findHistory: 'Nájdené cesty',
    findRequest: 'Na vašu žiadosť',
    findPick: 'Vyberte triedu auta',
    today: 'Dnes',
    findTrips: 'Vyhľadávať cesty',
    pastTrips: 'Predchádzajúce cesty',
    changeRequest: 'Zmeniť vyhľadávanie',
    priceMinIn: 'Min. cena v meste',
    priceMinOut: 'Min. cena mimo mesta',
    minKmIn: 'Min. km v meste',
    minKmOut: 'Min. km mimo mesta',
    pricePerKmIn: 'Cena / km v meste',
    pricePerKmOut: 'Cena / km mimo mesta',
    pricePerStayMinute: 'Cena / min státia',
    pricePerTripMinute: 'Cena / min cesty',
  },
});

export const faresLocale = new LocalizedStrings({
  en: {
    TariffPriceMin: 'The minimum cost ',
    TariffPriceInc: '\nincluded',
    TariffPriceIncLine: ' included',
    TariffPriceNextLine: '\nafter ',
    TariffPriceNext: 'after ',
    TariffPriceAwait: 'Awaiting:',
  },
  uk: {
    TariffPriceMin: 'Мінімальна вартість ',
    TariffPriceInc: '\nвключено',
    TariffPriceIncLine: ' включено',
    TariffPriceNextLine: '\nдалі ',
    TariffPriceNext: 'далі ',
    TariffPriceAwait: 'Очікування:',
  },
  ru: {
    TariffPriceMin: 'Минимальная стоимость ',
    TariffPriceInc: '\nвключено',
    TariffPriceIncLine: ' включено',
    TariffPriceNextLine: '\nдальше ',
    TariffPriceNext: 'дальше ',
    TariffPriceAwait: 'Ожидание: ',
  },
  sk: {
    TariffPriceMin: 'Minimálna cena',
    TariffPriceInc: '\nzahrnuté',
    TariffPriceIncLine: ' zahrnuté',
    TariffPriceNextLine: '\nďalej ',
    TariffPriceNext: 'ďalej ',
    TariffPriceAwait: 'Čakacia doba:',
  },
});
